# Your name and what you do
name: Volcano Universum
# Profile picture
picture: assets/images/profile.png

# your url: http://USERNAME.github.io
url: https://VolcanoUniversum.github.io/

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
twitter: VolcanoUnivers
github: VolcanoUniversum
email: volcano.universum@gmail.com
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: false

# do you want to display a skills section? true or false
skills: false

# add your skills here
skills-list:
    - HTML, Jade
    - CSS (Stylus, Sass, Less)
    - Javascript, NodeJS
    - AngularJS, ReactJS
    - Java, Android
    - Python
    - MySQL - MongoDB    
    - Git    

# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    FamilyPilot:
        name: HabitPilot
        description: |
            Every great changes in our lives start with change of our Habits. The HabitPilot is Habit Tracker which will lead you to successful path in your progress and changes.

            <h4>Features</h4>

            <ul>
                <li><strong>Unlimited</strong>: You are able to create unlimited amount of Habits without any restrictions.</li>
                <li><strong>Synchronization</strong>: All your Habits and progresses are seamlessly synchronize across your devices.</li>
                <li><strong>Free</strong>: Unlimited access to all features without any payment.</li>
                <li><strong>Privacy</strong>: All your settings & data are stored securely on your devices. HabitPilot does not use third-party analytics or ads.</li>
            </ul>

        url: https://VolcanoUniversum.github.io/HabitPilot/


# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: false

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
